services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_container
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/releases.sql:/docker-entrypoint-initdb.d/releases.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - internalnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  release_management_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app_container
    ports:
      - 3000:3000
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - internalnet

volumes:
  mysql_data:

networks:
  internalnet:
    driver: bridge
