name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and run Docker containers
      run: |
        docker compose up -d --build
        sleep 10
        curl -X GET http://localhost:3000/drift
